### ISSUE TITLE
ship the log to Amazon CloudWatch Logs

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-apisix#67]
Tha `apisix` container now ships the docker log to cloudwatch logs:

https://github.com/pahud/cdk-apisix/blob/13bbee89f6196c57752dd6bc85ade34e7f2dc511/src/apisix.ts#L94-L96

However, as `apisix` writes logs to its filesystem, we probably need to configure Firelens to ship the logs instead:

https://github.com/aws-samples/amazon-ecs-firelens-examples

Config sample: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/ecs-log-collection

**Comment by pahud** [comment]
Hi @starsz 

Can you tell me the exactly the log file path so I can implement this feature?

**Comment by starsz** [comment]
Sure.My pleasure.
There are two log files in apisix.

`/usr/local/apisix/logs/access.log`
`/usr/local/apisix/logs/error.log`

**Comment by pahud** [comment]
At this moment, I would prefer the upstream apisix docker container output its access.log and error.log to stdout and stderr. https://github.com/apache/apisix-docker/issues/149
